version: '3.9'

services:
  ubuntu-nginx:
    image: ubuntu/nginx
    container_name: ubuntu-nginx
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=GMT+7
      - NGINX_HOST="_"
      - NGINX_HOST_PORT="8000"
    volumes:
      - ./www/html/coming-soon:/var/www/html/coming-soon
      - ./nginx/templates/conf.template:/etc/nginx/templates/conf.template
      - ./nginx/ip_rules:/etc/nginx/ip_rules
    ports:
      # - "0.0.0.0:80:80"
      - "0.0.0.0:8000:8000"